# Generated by Django 4.0 on 2022-06-01 07:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('housing_type', models.CharField(choices=[('Condominium', 'Condominium'), ('HDB', 'HDB'), ('Landed', 'Landed')], max_length=11)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=7)),
                ('occupation_type', models.CharField(choices=[('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Employed', 'Employed')], max_length=10)),
                ('annual_income', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='api.household')),
                ('spouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.familymember')),
            ],
        ),
    ]
